server:
  port: 19200

spring:
  application:
    name: ex-account-srv

  datasource:
    url: jdbc:mysql://127.0.0.1:3308/ex_order?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  flyway:
    locations: classpath:db/migration
    enabled: false

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: DEFAULT
        enabled: true
        ephemeral: true