server:
  port: 9001

spring:
  application:
    name: ex-order

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ex_order?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  flyway:
    locations: classpath:db/migration
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # config-location: