server:
  port: 19100

spring:
  application:
    name: ex-order-srv

  datasource:
    url: jdbc:mysql://127.0.0.1:3308/ex_order?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  flyway:
    locations: classpath:db/migration
    enabled: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: DEFAULT
        enabled: true
        ephemeral: true
        # username:
        # access-key:
        # secret-key:
        # endpoint:
        # group: DEFAULT_GROUP
        # heart-beat-interval:
        # heart-beat-timeout:
        # instance-enabled: true
        # ip:
        # ip-delete-timeout:
        # log-name:
        # metadata:
        # nacos-properties:
        # namespace: dev
        # naming-load-cache-at-start: false
        # network-interface:
        # password:
        # port:
        # register-enabled: true
        # secure: false
        # service: ex-order
        # watch-delay:
        # weight: 1
        # watch:
        #   enabled: true



mybatis:
  mapper-locations: classpath:mapper/*.xml
  # config-location: